# Generated by Django 2.1.5 on 2019-09-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pointX', models.IntegerField(default=36)),
                ('pointY', models.IntegerField(default=24)),
            ],
        ),
    ]
