# Generated by Django 2.1.5 on 2019-09-05 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='account',
        ),
    ]
