# Generated by Django 2.1.5 on 2019-09-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Museums', '0002_auto_20190906_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='museums',
            name='discountAvailability',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='museums',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='museums',
            name='theme',
            field=models.IntegerField(default=0),
        ),
    ]
