# Generated by Django 2.1.5 on 2019-09-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shights', '0002_auto_20190906_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sights',
            name='content',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sights',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sights',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
